
server:
  port : 8080 
spring:
  application:
    name: UserPoolService
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: gunnerss
    initialization-mode: always
    data: classpath:data-postgres.sql
    platform: postgres
    dbcp2:
      validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.default_schema: public
    hibernate:
      ddl-auto: create-drop


    # url: jdbc:postgresql://localhost:5432/postgres
    # driver-class-name: org.postgresql.Driver
    # username: postgres
    # password: gunnerss
    # hibernate:
    #   ddl-auto: update