# spring.datasource.url: ${JDBC_DATABASE_URL:}
# spring.datasource.hikari.connection-timeout=30000
# spring.datasource.hikari.maximum-pool-size=10

# spring.profiles.active=production

# JUST THIS 
# server.port=${PORT:5000}

# logging:
#   file: logs/application-debug.log
server:
  port : 8080 
spring:
  data:
    mongodb:
      uri: mongodb://mongodb:gunnerss@localhost:27017
      database: portfoliomongodb
  output:
    ansi:
      enabled: DETECT
  application:
    name: UserPoolService
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: gunnerss
    initialization-mode: always
    data: classpath:data-postgres.sql
    platform: postgres
    dbcp2:
      validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.default_schema: public
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
management:
  endpoints:
    web:
      exposure:
        include: "*"